name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs: 
  build:
    uses: tiagocavaco/google-maps-draw-shape-lib/.github/workflows/build.yml@main

  release:
    name: Create new release
    
    needs: build

    runs-on: ubuntu-latest   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Release Changelog
        run: npx extract-changelog-release > RELEASE_CHANGELOG.md

      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          body_path: RELEASE_CHANGELOG.md
          draft: false
          prerelease: false

  npm:
    name: Publish package to npm

    needs: release

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}